document.getElementsByClassName("btn")[0].addEventListener("click",()=>{
    document.getElementsByClassName("content")[0].style.display="block".display="flex";
    document.getElementsByClassName("container")[0].style.background="#999999";
    document.getElementsByClassName("btn")[0].style.background="#8F8F8F";
})
document.getElementsByClassName("X")[0].addEventListener("click",()=>{
    document.getElementsByClassName("content")[0].style.display="none";
    document.getElementsByClassName("container")[0].style.background="white";
    document.getElementsByClassName("btn")[0].style.background="#E5E5E5";
})